services:
  nginx:
    image: nginx:1.23.1-alpine
    networks:
      - default
    ports:
      - 38000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./frontend/build:/www/web
    depends_on:
      - backend
      - frontend
    restart: always
  backend:
    image: wuretks.azurecr.io/nucktwillieren/pern-tutorial-backend:latest
    # build: ./backend
  frontend:
    image: wuretks.azurecr.io/nucktwillieren/pern-tutorial-frontend:latest
    # build: ./frontend
    